# Generated by Django 4.1.3 on 2022-11-23 10:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advert",
            name="locale",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="advert",
            name="translation_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name="advert",
            unique_together={("translation_key", "locale")},
        ),
    ]
